### PR TITLE
added MP Health check, fixes #11

### LINKED ISSUE #11: Add MP Health Page
Create page about MicroProfile Health

### PR DESCRIPTION
**Pull request by cicekhayri**
@phillip-kruger could you check if this is ok

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Looks good. I would reconsider the example. The /health are used by container orchestrations systems to decide should we take this pod out of services and restart it. Hitting an external URL would not be fixed by this. Just a thought ?

**Comment by cicekhayri** [comment]
Thanks @phillip-kruger for the feedback,, I really appreciate it,
I will try to update the example or If you already have an example we could use then it would be awesome :)

**Comment by phillip-kruger** [comment]
I have this one, but you can make the same argument as above, this one checks a database connection, so a restart might fix it, but not definitely.

https://github.com/phillip-kruger/microprofile-demo/blob/master/membership/src/main/java/com/github/phillipkruger/membership/health/MembershipHealthCheck.java

**Comment by cicekhayri** [comment]
Are you ok if I add the code snippet to the ebook for more examples

**Comment by phillip-kruger** [comment]
Yes sure :)

**Review by phillip-kruger — APPROVED** [review]

**Pull request merged**
